apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - mutatingwebhook.yaml
  - deployment.yaml
  - service.yaml
  - rbac.yaml

configurations:
  - kustomizeconfig.yaml

secretGenerator:
- name: cloud-secrets-certs
  namespace: cloud-secrets
  files:
  - ca.crt=./build/certs/ca.pem
  - tls.crt=./build/certs/server.pem
  - tls.key=./build/certs/server-key.pem
  type: "Opaque"

vars:
  - name: TLSCERT
    objref:
      kind: Secret
      version: v1
      name: cloud-secrets-certs
    fieldref:
      fieldpath: data[ca.crt]