apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: cloud-secrets
  labels:
    app.kubernetes.io/name: cloud-secrets
webhooks:
- name: cloud-secrets.daisaru11.dev
  clientConfig:
    service:
      name: cloud-secrets
      path: "/mutate"
      namespace: cloud-secrets
    caBundle: $(TLSCERT)
  rules:
    - operations: ["CREATE", "UPDATE"]
      apiGroups: [""]
      apiVersions: ["v1"]
      resources: ["deployments", "jobs", "pods", "statefulsets"]
