apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample
  labels:
    name: sample
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample
  template:
    metadata:
      labels:
        app: sample
      name: sample
      annotations:
        cloud-secrets.daisaru11.dev/enabled: "true"
    spec:
      containers:
        - name: sample
          image: alpine:latest
          command: ["/bin/sh", "-c"]
          args: ["env && tail -f /dev/null"]
          env:
            - name: FOO
              value: "cloud-secrets://nop/foo"
            - name: BAR
              value: "cloud-secrets://nop/bar"
