apiVersion: v1
kind: Service
metadata:
  name: cloud-secrets
  labels:
    app.kubernetes.io/name: cloud-secrets
  namespace: cloud-secrets
spec:
  ports:
  - port: 443
    targetPort: 8080
  selector:
    app.kubernetes.io/name: cloud-secrets